server:
  zkUrl: 127.0.0.1:2181
  zkTimeOut: 5000
  id: architecture
  port: 16888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest
    username: root
   # password: 123321
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml
